namespace OpenKh.Tools.ModsManager.Core;

internal static class LegacyModFormat
{
    public const string PcPatchMarkerFileName = ".openkh-pcpatch";

    private static readonly string[] PcPatchNames =
    [
        "KH1PCPATCH",
        "KH2PCPATCH",
        "COMPCPATCH",
        "BBSPCPATCH",
        "DDDPCPATCH"
    ];

    public static bool IsPcPatch(string directory, ModMetadata? metadata)
    {
        if (File.Exists(Path.Combine(directory, PcPatchMarkerFileName)))
            return true;

        // Older imports predate the marker file but have metadata generated by the PC Patch importer.
        return PcPatchNames.Any(name =>
            metadata?.Title?.EndsWith($" ({name})", StringComparison.OrdinalIgnoreCase) == true ||
            metadata?.Description?.Equals(
                $"Metadata generated for an imported {name} modification.",
                StringComparison.OrdinalIgnoreCase) == true);
    }
}
