name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        with:
          target: minor
          approve: true
          command: squash and merge
          github-token: ${{ secrets.GITHUB_TOKEN }}
