name: .NET

on:
  push:
    branches: [ gui/avalonia ]
  pull_request:
    branches: [ gui/avalonia ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build ./OpenKh.Tools.BarTool/OpenKh.Tools.BarTool.csproj
